#!/usr/bin/env python

import sys, os, re

def run():
	os.system('rm -f pics/*')
	for filename in os.listdir('timeslice2d/'):
		fileout = 'pics/' + filename[0:-4] + '.png' 
		command1 = ' "filename=' + "'timeslice2d/" + filename + "'" + '"' 
		command2 = ' "fileout=' + "'" + fileout + "'" + '"' 
		os.system('gnuplot -e ' + command1 + ' -e ' + command2 + ' gimmepng.plg')
	os.system('convert -delay 1 -loop 0 pics/*.png wave.gif')

run()
