#!/bin/bash
echo "Removing old data"
rm -f data/*ppm 
echo "Compiling"
gfortran draw.f90
./a.out
echo "Running"
ffmpeg -r 30 -i data/%04d\ \ \ \ \ \ .ppm -c:v libx264 -crf 18 -pix_fmt yuv420p out.mp4
xdg-open out.mp4
